# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/eeae903a-d5cd-4a0d-865d-9d7179a0d811";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/99672515-3af7-46f3-ba97-bc0db70c730e"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
